### ISSUE TITLE
client authentication failed  on mendeley website

### ISSUE THREAD

**Issue by flyinskybtx** [ONLYOFFICE/plugin-mendeley#29] opened 2020-12-08 11:39 UTC
I have filled the application ID, and when I login, the Mendeley site blocked me,  and reads :

"An invalid request was made by a third-party app

Client authentication failed"

**Comment by mschepers188** [comment] 2022-01-20 20:36
I get exactly the same error.

**Comment by DenisDeeSign** [comment] 2022-01-21 07:55
Hi @flyinskybtx and @mschepers188,
please specify what product are you using, Document Server or Desktop Editors.

**Comment by mschepers188** [comment] 2022-01-23 09:26
My apologies, my problem is for the Desktop version. Every time I'm redirected to the browser for authentication I get the above error.

**Comment by DenisDeeSign** [comment] 2022-01-24 07:18
Duplicate of #33

**Closed** 2022-01-24 07:18 UTC
